# Generated by Django 4.2.4 on 2023-09-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvantagesOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_text', models.CharField(max_length=14)),
                ('middle_text', models.CharField(max_length=14)),
                ('bottom_text', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='MenuOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=14)),
                ('link', models.URLField()),
            ],
        ),
    ]
